use std::path::PathBuf;
use std::process::Command;

/// Install a git hook
pub fn install_hook(hook_type: &str) -> anyhow::Result<()> {
    // Verify we're in a git repo
    let git_dir = PathBuf::from(".git");
    if !git_dir.exists() {
        // Try git rev-parse
        let output = Command::new("git")
            .args(["rev-parse", "--git-dir"])
            .output()
            .map_err(|e| anyhow::anyhow!("Not in a git repository: {}", e))?;

        if !output.status.success() {
            anyhow::bail!("Not in a git repository. Run 'mneme-g install' from a git repo.");
        }
    }

    let hooks_dir = PathBuf::from(".git").join("hooks");
    std::fs::create_dir_all(&hooks_dir)?;

    match hook_type {
        "pre-commit" => install_pre_commit(&hooks_dir)?,
        "commit-msg" => install_commit_msg(&hooks_dir)?,
        other => anyhow::bail!(
            "Unknown hook type: {}. Supported: pre-commit, commit-msg",
            other
        ),
    }

    println!("✓ {} hook installed.", hook_type);
    Ok(())
}

fn install_pre_commit(hooks_dir: &PathBuf) -> anyhow::Result<()> {
    let hook_path = hooks_dir.join("pre-commit");

    let hook_content = r#"#!/usr/bin/env bash
set -euo pipefail

# mneme-guardian pre-commit hook
# Generated by: mneme-g install

exec mneme-g run
"#;

    std::fs::write(&hook_path, hook_content)?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&hook_path, std::fs::Permissions::from_mode(0o755))?;
    }

    Ok(())
}

fn install_commit_msg(hooks_dir: &PathBuf) -> anyhow::Result<()> {
    let hook_path = hooks_dir.join("commit-msg");

    let hook_content = r#"#!/usr/bin/env bash
set -euo pipefail

# mneme-guardian commit-msg hook
# Generated by: mneme-g install

# Check conventional commit format
COMMIT_MSG=$(cat "$1")
if ! echo "$COMMIT_MSG" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\(.+\))?: .{1,}$"; then
    echo "⚠  Commit message does not follow Conventional Commits format."
    echo "   Expected: feat(scope): message"
    echo "   Examples:"
    echo "     feat(auth): add JWT middleware"
    echo "     fix(db): handle null relationship"
    echo "     docs(readme): update installation"
    exit 1
fi
"#;

    std::fs::write(&hook_path, hook_content)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&hook_path, std::fs::Permissions::from_mode(0o755))?;
    }

    Ok(())
}

/// Uninstall mneme-guardian hooks
pub fn uninstall_hook() -> anyhow::Result<()> {
    let hooks_dir = PathBuf::from(".git").join("hooks");
    let mut removed = false;

    for name in &["pre-commit", "commit-msg"] {
        let path = hooks_dir.join(name);
        if path.exists() {
            // Check if it's our hook
            if let Ok(content) = std::fs::read_to_string(&path) {
                if content.contains("mneme-guardian") {
                    std::fs::remove_file(&path)?;
                    println!("✓ Removed hook: {}", name);
                    removed = true;
                }
            }
        }
    }

    if !removed {
        println!("ℹ No mneme-guardian hooks found.");
    }

    Ok(())
}
